### ISSUE TITLE
EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription

### ISSUE THREAD

**Issue by vasudevjogani** [odemolliens/react-native-sim-cards-manager#12]
When I have pass valid "confirmationCode" and "address" then got error "EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription"

From updated code version"1.0.2"

**Comment by odemolliens** [comment]
Hello,

We just published a new version [1.0.3](https://github.com/odemolliens/react-native-sim-cards-manager/releases/tag/1.0.3)

Can you try again?

**Comment by vasudevjogani** [comment]
**Configuration:-**
Device :- Samsung s21 ultra with no sim! 
OS - 12 (31 API level) 
Package name = com.example.reactnativesimcardsmanager
Activation code= 1$rsp-0003.oberthur.net$NA1D8-SENZL-9OJPX-677I0
Address = rsp-0003.oberthur.net
Confirmation code = NA1D8-SENZL-9OJPX-677I0


**Case 1** 
Settings:
When library support Target version = 31, compile version 31. 
Example Target Version = 30 and compile version 30.

Result =  When clicking on ACTIVATE ESIM 
Getting permission popup “Allow ‘package name’ to access your phone’s eUICC Profile?

After clicking on “Allow” getting below error. 
**“2 EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription”** 


**Case 2** 
Settings:
When library support Target version = 31, compile version 31. 
Example Target Version = 31 and compile version 31


Result= When clicking on ACTIVATE ESIM
Getting permission popup “Allow ‘package name’ to access your phone’s eUICC Profile? With below ERROR. 
**E/Error: 3 EMBEDDED_SUBSCRIPTION_RESULT_RESOLVABLE_ERROR - Can't setup eSim du to Activity errornull**

After clicking o
![Screenshot_20220429_141604](https://user-images.githubusercontent.com/26995623/165913580-f7b06e38-44f1-4ba3-8256-14831a8bc7bc.png)
n “Allow” getting below error 
**“2 EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription”**
![Screenshot_20220429_140448](https://user-images.githubusercontent.com/26995623/165913561-5171b55b-7e4c-482c-8b83-de0c5400aa74.png)

**Comment by vasudevjogani** [comment]
Is library code issue? 

is LPA(Activation code) profile issue?

is Activation code is already used? if Yes, how to identify?

@odemolliens

**Comment by odemolliens** [comment]
Hello @vasudevjogani 

We released 1.0.4 which provide more details about the error on the Android bridge

**Comment by monica-ty** [comment]
Hi @odemolliens,

I'm still getting this issue in Android 12: [Error: EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription].

It happens in almost all Android 12 devices including Pixel 4/5/6/7, OPPO X3/X5, Sony Xperia, Microsoft Surface Duo, etc. And we think it might be because of the PendingIntent Flag you use.

Could you investigate this issue? I'm using the updated version 1.0.10.

**Comment by odemolliens** [comment]
Hello,

This ticket is closed, please open a new one. 

Did you check the adb console?

**Comment by odemolliens** [comment]
@monica-ty ?

**Comment by Daidalos117** [comment]
@monica-ty did you solve it?
I am facing the same, not sure how to debug it :(

**Comment by monica-ty** [comment]
@Daidalos117 No, they can only setup by scanning a QR code with the built-in camera.

**Comment by odemolliens** [comment]
Can you check what's going on in the Logcat logs?

**Comment by Daidalos117** [comment]
@odemolliens what to look for?

**Comment by Daidalos117** [comment]
@odemolliens what tag to search for in logs?

**Comment by odemolliens** [comment]
Don't use any filter on Logcat, error messages are coming from the system. As soon as you start the eSim process, check what's going on in parallel on Logcat.

Did you try on a different version that Android 12, is it working?
