### ISSUE TITLE
Error installing the esim on android

### ISSUE THREAD

**Issue by Daidalos117** [odemolliens/react-native-sim-cards-manager#39]
Hello,

first I want to thank for nice library! I have been trying the setup of esim for a while now. On iOS, there is no problem, esim is successfully installed. But on android, I am getting error 

> Error: EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription

What is interesting, after that I am unable to open SIM card manager on the device, I am getting 

> Wait for your eSIM to finish being set up before using the SIM manager.

Only option how to make it work again is to factory reset the device. Seems like something gets hanging somewhere. Any idea what it can be?
Device: Galaxy S22
Android 13

Thanks for any input!

**Comment by Daidalos117** [comment]
any idea?

**Comment by Daidalos117** [comment]
Ok, I found out what was the issue. Documentation describes that we need to use the android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS. But that permission is available only to system apps, which Android studio correctly reports. (but I didn't know since of course as RN developer I am using Webstorm)
<img width="400" alt="Snímek obrazovky 2023-01-30 v 14 09 34" src="https://user-images.githubusercontent.com/15905269/215486673-f8cc0880-3f6d-4427-a35d-f16196d22ff0.png">
Solution for normal apps is [obtaining carrier privileges](https://source.android.com/docs/core/connect/esim-overview#carrier-privileges). After that, everything works fine. I think it would be pretty nice to mention this to documentation

**Comment by odemolliens** [comment]
Thanks for the feedback @Daidalos117. I just updated the README. Any PR is welcome ;)

**Comment by AbrorEsonov** [comment]
> Ok, I found out what was the issue. Documentation describes that we need to use the android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS. But that permission is available only to system apps, which Android studio correctly reports. (but I didn't know since of course as RN developer I am using Webstorm) <img alt="Snímek obrazovky 2023-01-30 v 14 09 34" width="400" src="https://user-images.githubusercontent.com/15905269/215486673-f8cc0880-3f6d-4427-a35d-f16196d22ff0.png"> Solution for normal apps is [obtaining carrier privileges](https://source.android.com/docs/core/connect/esim-overview#carrier-privileges). After that, everything works fine. I think it would be pretty nice to mention this to documentation

You mean when i have to download eSim through my app i have to add android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS permission to AndroidManifest? EuiccManager's downloadSubscription method requires this permission

**Comment by AbrorEsonov** [comment]
@Daidalos117 Thanks, I have obtained carrier privileges, eSim's metadata includes my app's SHA-256 and package name, I have checked them in Logcat, I have tested my app on release mode, set up eSim worked but I have published my app on play store, users cannot set up eSim, EMBEDDED_SUBSCRIPTION_RESULT_ERROR error is occurring, my app is written on Flutter))

**Comment by AbrorEsonov** [comment]
Can you guys please help your experience @odemolliens @Daidalos117 
val telephonyManager =
        context?.getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager
    val haspriv = telephonyManager.hasCarrierPrivileges()
    Log.d(TAG, "priv: $haspriv")
    
  this code is always returning false, LogCat says **Caller does not have carrier privilege in metadata.**

**Comment by lucle** [comment]
@AbrorEsonov Did you resolve the problem? I also face this issue but still not find any solution.
